### ISSUE TITLE
Spamming comment sections

### ISSUE THREAD

**Issue by dagdrommer** [mirsella/reddit-sl-bot#1]
Hey,

your bot is out of control. Spamming the comments over and over with the sl locomotive.

Cheers ;)

**Comment by mirsella** [comment]
hey thanks for the info.

I was testing some things and rerun the bot from another environnement which has a older config file, with older timestamp, so the bot resend the messages. I should add a failsafe but it should be good now anyway. I'm very sorry for the inconveniences. have a good say
